# Generated by Django 4.0.4 on 2022-06-01 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование бренда')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование продукта')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('vendor_code', models.CharField(max_length=50, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('sold', models.BooleanField(verbose_name='Продан')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Дополнительная информация')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего посещения')),
                ('access_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Количество просмотров')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.brand', verbose_name='Наименование бренда')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Общая категория')),
                ('icon', models.ImageField(blank=True, upload_to=shop.models.user_directory_path_1, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Общая категория',
                'verbose_name_plural': 'Общие категории',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование поставщика')),
                ('inn', models.CharField(blank=True, max_length=15, verbose_name='ИНН')),
                ('pdv', models.CharField(blank=True, max_length=15, verbose_name='Номер свидетельства НДС')),
                ('egrpou', models.CharField(blank=True, max_length=15, verbose_name='ЕГРПОУ')),
                ('bank', models.CharField(blank=True, max_length=50, verbose_name='Банк')),
                ('mfo', models.CharField(blank=True, max_length=8, verbose_name='МФО')),
                ('checking_account', models.CharField(blank=True, max_length=50, verbose_name='Расчетный счет')),
                ('tel', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронный адрес')),
                ('person', models.CharField(max_length=20, verbose_name='Контактное лицо')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Дата внесения в базу')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи')),
                ('sale_date', models.DateField(auto_now_add=True, verbose_name='Дата продажи')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Наименование продукта')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(blank=True, verbose_name='Оценка')),
                ('review_text', models.CharField(blank=True, max_length=255, verbose_name='Текст отзыва')),
                ('review_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Отзыв на продукт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, upload_to=shop.models.user_directory_path, verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, upload_to=shop.models.user_directory_path, verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, upload_to=shop.models.user_directory_path, verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, upload_to=shop.models.user_directory_path, verbose_name='Изображение 4')),
                ('image_5', models.ImageField(blank=True, upload_to=shop.models.user_directory_path, verbose_name='Изображение 5')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товара',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_1', models.CharField(blank=True, max_length=100, verbose_name='1')),
                ('feature_2', models.CharField(blank=True, max_length=100, verbose_name='2')),
                ('feature_3', models.CharField(blank=True, max_length=100, verbose_name='3')),
                ('feature_4', models.CharField(blank=True, max_length=100, verbose_name='4')),
                ('feature_5', models.CharField(blank=True, max_length=100, verbose_name='5')),
                ('feature_6', models.CharField(blank=True, max_length=100, verbose_name='6')),
                ('feature_7', models.CharField(blank=True, max_length=100, verbose_name='7')),
                ('feature_8', models.CharField(blank=True, max_length=100, verbose_name='8')),
                ('feature_9', models.CharField(blank=True, max_length=100, verbose_name='9')),
                ('feature_10', models.CharField(blank=True, max_length=100, verbose_name='10')),
                ('feature_11', models.CharField(blank=True, max_length=100, verbose_name='11')),
                ('feature_12', models.CharField(blank=True, max_length=100, verbose_name='12')),
                ('feature_13', models.CharField(blank=True, max_length=100, verbose_name='13')),
                ('feature_14', models.CharField(blank=True, max_length=100, verbose_name='14')),
                ('feature_15', models.CharField(blank=True, max_length=100, verbose_name='15')),
                ('feature_16', models.CharField(blank=True, max_length=100, verbose_name='16')),
                ('feature_17', models.CharField(blank=True, max_length=100, verbose_name='17')),
                ('feature_18', models.CharField(blank=True, max_length=100, verbose_name='18')),
                ('feature_19', models.CharField(blank=True, max_length=100, verbose_name='19')),
                ('feature_20', models.CharField(blank=True, max_length=100, verbose_name='20')),
                ('feature_21', models.CharField(blank=True, max_length=100, verbose_name='21')),
                ('feature_22', models.CharField(blank=True, max_length=100, verbose_name='22')),
                ('feature_23', models.CharField(blank=True, max_length=100, verbose_name='23')),
                ('feature_24', models.CharField(blank=True, max_length=100, verbose_name='24')),
                ('feature_25', models.CharField(blank=True, max_length=100, verbose_name='25')),
                ('feature_26', models.CharField(blank=True, max_length=100, verbose_name='26')),
                ('feature_27', models.CharField(blank=True, max_length=100, verbose_name='27')),
                ('feature_28', models.CharField(blank=True, max_length=100, verbose_name='28')),
                ('feature_29', models.CharField(blank=True, max_length=100, verbose_name='29')),
                ('feature_30', models.CharField(blank=True, max_length=100, verbose_name='30')),
                ('feature_31', models.CharField(blank=True, max_length=100, verbose_name='31')),
                ('feature_32', models.CharField(blank=True, max_length=100, verbose_name='32')),
                ('feature_33', models.CharField(blank=True, max_length=100, verbose_name='33')),
                ('feature_34', models.CharField(blank=True, max_length=100, verbose_name='34')),
                ('feature_35', models.CharField(blank=True, max_length=100, verbose_name='35')),
                ('feature_36', models.CharField(blank=True, max_length=100, verbose_name='36')),
                ('feature_37', models.CharField(blank=True, max_length=100, verbose_name='37')),
                ('feature_38', models.CharField(blank=True, max_length=100, verbose_name='38')),
                ('feature_39', models.CharField(blank=True, max_length=100, verbose_name='39')),
                ('feature_40', models.CharField(blank=True, max_length=100, verbose_name='40')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Характеристики продукта',
                'verbose_name_plural': 'Характеристики продуктов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(to='shop.supplier', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(verbose_name='Лайк')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('income_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Входящая цена')),
                ('income_date', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Наименование продукта')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
            },
        ),
        migrations.CreateModel(
            name='CategoryFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name_1', models.CharField(blank=True, max_length=100, verbose_name='1')),
                ('feature_name_2', models.CharField(blank=True, max_length=100, verbose_name='2')),
                ('feature_name_3', models.CharField(blank=True, max_length=100, verbose_name='3')),
                ('feature_name_4', models.CharField(blank=True, max_length=100, verbose_name='4')),
                ('feature_name_5', models.CharField(blank=True, max_length=100, verbose_name='5')),
                ('feature_name_6', models.CharField(blank=True, max_length=100, verbose_name='6')),
                ('feature_name_7', models.CharField(blank=True, max_length=100, verbose_name='7')),
                ('feature_name_8', models.CharField(blank=True, max_length=100, verbose_name='8')),
                ('feature_name_9', models.CharField(blank=True, max_length=100, verbose_name='9')),
                ('feature_name_10', models.CharField(blank=True, max_length=100, verbose_name='10')),
                ('feature_name_11', models.CharField(blank=True, max_length=100, verbose_name='11')),
                ('feature_name_12', models.CharField(blank=True, max_length=100, verbose_name='12')),
                ('feature_name_13', models.CharField(blank=True, max_length=100, verbose_name='13')),
                ('feature_name_14', models.CharField(blank=True, max_length=100, verbose_name='14')),
                ('feature_name_15', models.CharField(blank=True, max_length=100, verbose_name='15')),
                ('feature_name_16', models.CharField(blank=True, max_length=100, verbose_name='16')),
                ('feature_name_17', models.CharField(blank=True, max_length=100, verbose_name='17')),
                ('feature_name_18', models.CharField(blank=True, max_length=100, verbose_name='18')),
                ('feature_name_19', models.CharField(blank=True, max_length=100, verbose_name='19')),
                ('feature_name_20', models.CharField(blank=True, max_length=100, verbose_name='20')),
                ('feature_name_21', models.CharField(blank=True, max_length=100, verbose_name='21')),
                ('feature_name_22', models.CharField(blank=True, max_length=100, verbose_name='22')),
                ('feature_name_23', models.CharField(blank=True, max_length=100, verbose_name='23')),
                ('feature_name_24', models.CharField(blank=True, max_length=100, verbose_name='24')),
                ('feature_name_25', models.CharField(blank=True, max_length=100, verbose_name='25')),
                ('feature_name_26', models.CharField(blank=True, max_length=100, verbose_name='26')),
                ('feature_name_27', models.CharField(blank=True, max_length=100, verbose_name='27')),
                ('feature_name_28', models.CharField(blank=True, max_length=100, verbose_name='28')),
                ('feature_name_29', models.CharField(blank=True, max_length=100, verbose_name='29')),
                ('feature_name_30', models.CharField(blank=True, max_length=100, verbose_name='30')),
                ('feature_name_31', models.CharField(blank=True, max_length=100, verbose_name='31')),
                ('feature_name_32', models.CharField(blank=True, max_length=100, verbose_name='32')),
                ('feature_name_33', models.CharField(blank=True, max_length=100, verbose_name='33')),
                ('feature_name_34', models.CharField(blank=True, max_length=100, verbose_name='34')),
                ('feature_name_35', models.CharField(blank=True, max_length=100, verbose_name='35')),
                ('feature_name_36', models.CharField(blank=True, max_length=100, verbose_name='36')),
                ('feature_name_37', models.CharField(blank=True, max_length=100, verbose_name='37')),
                ('feature_name_38', models.CharField(blank=True, max_length=100, verbose_name='38')),
                ('feature_name_39', models.CharField(blank=True, max_length=100, verbose_name='39')),
                ('feature_name_40', models.CharField(blank=True, max_length=100, verbose_name='40')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'verbose_name': 'Характеристики категории',
                'verbose_name_plural': 'Характеристики категорий',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.supercategory'),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=30, verbose_name='Адресс')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
    ]
