# Generated by Django 4.0.4 on 2022-07-04 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='dislike',
            field=models.BooleanField(blank=True, null=True, verbose_name='Дизлайк'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва'),
        ),
    ]
