# Generated by Django 4.0.4 on 2022-07-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_like_dislike_review_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка'),
        ),
    ]
