# Generated by Django 4.0.4 on 2022-09-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_stock_price_stock_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
