# Generated by Django 4.0.4 on 2022-09-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_buyer_email_alter_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_10_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='10'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_10_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='10'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_10_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='10'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_11_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='11'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_11_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='11'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_11_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='11'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_12_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='12'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_12_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='12'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_12_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='12'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_13_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='13'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_13_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='13'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_13_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='13'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_14_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='14'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_14_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='14'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_14_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='14'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_15_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='15'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_15_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='15'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_15_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='15'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_16_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='16'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_16_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='16'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_16_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='16'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_17_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='17'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_17_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='17'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_17_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='17'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_18_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='18'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_18_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='18'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_18_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='18'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_19_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='19'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_19_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='19'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_19_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='19'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_1_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_1_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_1_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_20_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='20'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_20_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='20'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_20_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='20'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_21_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='21'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_21_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='21'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_21_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='21'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_22_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='22'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_22_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='22'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_22_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='22'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_23_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='23'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_23_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='23'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_23_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='23'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_24_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='24'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_24_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='24'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_24_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='24'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_25_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='25'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_25_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='25'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_25_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='25'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_26_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='26'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_26_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='26'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_26_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='26'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_27_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='27'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_27_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='27'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_27_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='27'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_28_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='28'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_28_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='28'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_28_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='28'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_29_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='29'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_29_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='29'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_29_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='29'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_2_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_2_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_2_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_30_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='30'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_30_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='30'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_30_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='30'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_31_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='31'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_31_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='31'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_31_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='31'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_32_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='32'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_32_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='32'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_32_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='32'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_33_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='33'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_33_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='33'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_33_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='33'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_34_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='34'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_34_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='34'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_34_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='34'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_35_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='35'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_35_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='35'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_35_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='35'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_36_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='36'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_36_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='36'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_36_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='36'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_37_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='37'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_37_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='37'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_37_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='37'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_38_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='38'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_38_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='38'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_38_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='38'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_39_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='39'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_39_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='39'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_39_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='39'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_3_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='3'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_3_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='3'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_3_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='3'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_40_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='40'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_40_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='40'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_40_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='40'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_4_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='4'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_4_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='4'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_4_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='4'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_5_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='5'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_5_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='5'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_5_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='5'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_6_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='6'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_6_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='6'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_6_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='6'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_7_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='7'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_7_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='7'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_7_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='7'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_8_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='8'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_8_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='8'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_8_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='8'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_9_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='9'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_9_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='9'),
        ),
        migrations.AddField(
            model_name='categoryfeatures',
            name='feature_name_9_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='9'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Наименование продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Наименование продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Наименование продукта'),
        ),
        migrations.AddField(
            model_name='review',
            name='dislike_num',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Количество дизлайков'),
        ),
        migrations.AddField(
            model_name='review',
            name='like_num',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Количество лайков'),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Общая категория'),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Общая категория'),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Общая категория'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Наименование поставщика'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Наименование поставщика'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Наименование поставщика'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='person_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='person_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='person_uk',
            field=models.CharField(max_length=20, null=True, verbose_name='Контактное лицо'),
        ),
    ]
