# Generated by Django 4.0.4 on 2022-09-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_category_name_en_category_name_ru_category_name_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
