# Generated by Django 4.0.4 on 2022-09-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='grade',
        ),
    ]
